#!/bin/sh

if [ "x$BASH_SOURCE" != "x" ]; then
	d=`dirname $BASH_SOURCE`
else
	d=`dirname $0`
fi

EPPY_BASE=`(cd "$d"; pwd)`
export EPPY_BASE


PATH=$EPPY_BASE/bin:$PATH
export PATH

. $EPPY_BASE/venv/bin/activate

PYTHONPATH=$EPPY_BASE/src

PS1="[eppy]"`echo $PS1 | sed -e 's/^(venv)//'`" "

if [ "x$1" != "x" ]; then
	exec "$@"
fi
